# Generated by Django 4.2.27 on 2025-12-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('license_id', models.CharField(max_length=6, unique=True, verbose_name='Lisans No')),
            ],
            options={
                'verbose_name': 'Eğitici',
                'verbose_name_plural': 'Eğiticiler',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('license_id', models.CharField(max_length=6, unique=True, verbose_name='Lisans No')),
                ('role', models.CharField(choices=[('DOCTOR', 'İşyeri Hekimi'), ('SPECIALIST', 'İş Güvenliği Uzmanı')], max_length=20, verbose_name='Görevi')),
            ],
            options={
                'verbose_name': 'Profesyonel',
                'verbose_name_plural': 'Profesyoneller',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İşyeri Adı')),
                ('detsis_number', models.CharField(max_length=50, unique=True, verbose_name='DETSİS No')),
            ],
            options={
                'verbose_name': 'İşyeri',
                'verbose_name_plural': 'İşyerleri',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('tckn', models.CharField(max_length=11, unique=True, verbose_name='TCKN')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.workplace', verbose_name='İşyeri')),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('notes', models.TextField(verbose_name='Notlar')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.professional', verbose_name='Denetleyen')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workplace', verbose_name='İşyeri')),
            ],
            options={
                'verbose_name': 'Denetim',
                'verbose_name_plural': 'Denetimler',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('notes', models.TextField(verbose_name='Notlar/Sonuç')),
                ('professional', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, to='core.professional', verbose_name='Hekim')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Sağlık Muayenesi',
                'verbose_name_plural': 'Sağlık Muayeneleri',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('topic', models.CharField(max_length=255, verbose_name='Konu')),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.educator', verbose_name='Eğitici')),
                ('workers', models.ManyToManyField(to='core.worker', verbose_name='Katılımcılar')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workplace', verbose_name='İşyeri')),
            ],
            options={
                'verbose_name': 'İSG Eğitimi',
                'verbose_name_plural': 'İSG Eğitimleri',
            },
        ),
    ]
