# Generated by Django 4.2.27 on 2025-12-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Meslek Adı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meslek",
                "verbose_name_plural": "Meslekler",
            },
        ),
        migrations.AddField(
            model_name="examination",
            name="audiometry",
            field=models.BooleanField(default=False, verbose_name="Odyometri"),
        ),
        migrations.AddField(
            model_name="examination",
            name="biochemistry",
            field=models.BooleanField(default=False, verbose_name="Biyokimya"),
        ),
        migrations.AddField(
            model_name="examination",
            name="decision",
            field=models.CharField(
                choices=[
                    ("FIT", "Çalışmaya Elverişlidir"),
                    ("CONDITIONAL", "Şartlı Olarak Çalışmaya Elverişlidir"),
                ],
                default="FIT",
                max_length=20,
                verbose_name="Karar",
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="decision_conditions",
            field=models.TextField(blank=True, null=True, verbose_name="Şartlar"),
        ),
        migrations.AddField(
            model_name="examination",
            name="hemogram",
            field=models.BooleanField(default=False, verbose_name="Hemogram"),
        ),
        migrations.AddField(
            model_name="examination",
            name="hepatitis_b_vaccine",
            field=models.BooleanField(default=False, verbose_name="Hepatit B Aşısı"),
        ),
        migrations.AddField(
            model_name="examination",
            name="hepatitis_b_value",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Anti-HbS Değeri"
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="radiology",
            field=models.BooleanField(default=False, verbose_name="Radyoloji"),
        ),
        migrations.AddField(
            model_name="examination",
            name="serology",
            field=models.BooleanField(default=False, verbose_name="Seroloji"),
        ),
        migrations.AddField(
            model_name="examination",
            name="sft",
            field=models.BooleanField(default=False, verbose_name="SFT"),
        ),
        migrations.AddField(
            model_name="examination",
            name="tetanus_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tetanoz Aşısı Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="tetanus_vaccine",
            field=models.BooleanField(default=False, verbose_name="Tetanoz Aşısı"),
        ),
        migrations.AddField(
            model_name="examination",
            name="work_accident",
            field=models.BooleanField(default=False, verbose_name="İş Kazası"),
        ),
        migrations.AddField(
            model_name="examination",
            name="work_accident_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="İş Kazası Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Doğum Tarihi"),
        ),
        migrations.AddField(
            model_name="worker",
            name="chronic_diseases",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Kronik Hastalıklar"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Kadın"), ("M", "Erkek")],
                max_length=1,
                null=True,
                verbose_name="Cinsiyet",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notlar"),
        ),
        migrations.AddField(
            model_name="workplace",
            name="hazard_class",
            field=models.CharField(
                choices=[
                    ("LOW", "Az Tehlikeli"),
                    ("MEDIUM", "Tehlikeli"),
                    ("HIGH", "Çok Tehlikeli"),
                ],
                default="LOW",
                max_length=10,
                verbose_name="Tehlike Sınıfı",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notlar/Sonuç"),
        ),
        migrations.AddField(
            model_name="worker",
            name="profession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.profession",
                verbose_name="Meslek",
            ),
        ),
    ]
