# Generated by Django 4.2.27 on 2025-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profession_examination_audiometry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examination",
            name="hepatitis_b_value",
        ),
        migrations.RemoveField(
            model_name="examination",
            name="work_accident",
        ),
        migrations.RemoveField(
            model_name="examination",
            name="work_accident_date",
        ),
        migrations.AlterField(
            model_name="examination",
            name="hepatitis_b_vaccine",
            field=models.BooleanField(
                default=False, verbose_name="Hepatit B Aşısı Önerildi"
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="tetanus_vaccine",
            field=models.BooleanField(
                default=False, verbose_name="Tetanoz Aşısı Önerildi"
            ),
        ),
    ]
