# Generated by Django 4.2.27 on 2025-12-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profession_examination_audiometry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="special_note",
            field=models.TextField(blank=True, null=True, verbose_name="Özel Not"),
        ),
        migrations.AddField(
            model_name="workplace",
            name="special_note",
            field=models.TextField(blank=True, null=True, verbose_name="Özel Not"),
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Birim Adı")),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="core.workplace",
                        verbose_name="İşyeri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Birim",
                "verbose_name_plural": "Birimler",
                "unique_together": {("name", "workplace")},
            },
        ),
        migrations.AddField(
            model_name="worker",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="core.facility",
                verbose_name="Birim",
            ),
        ),
    ]
