# Generated by Django 4.2.27 on 2025-12-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_examination_hepatitis_b_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="caution_note",
            field=models.TextField(blank=True, null=True, verbose_name="Not"),
        ),
        migrations.AddField(
            model_name="examination",
            name="is_caution",
            field=models.BooleanField(default=False, verbose_name="Uyarı notu"),
        ),
    ]
