# Generated by Django 4.2.27 on 2025-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_examination_caution_note_examination_is_caution"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="first_aid_certificate",
            field=models.BooleanField(
                default=False, verbose_name="İlkyardım Sertifikası"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="first_aid_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sertifika Bitiş Tarihi"
            ),
        ),
    ]
