# Generated by Django 4.2.27 on 2025-12-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_worker_first_aid_certificate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Bina/Birim Adı"),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="core.workplace",
                        verbose_name="İşyeri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bina/Birim",
                "verbose_name_plural": "Binalar/Birimler",
            },
        ),
        migrations.AddField(
            model_name="worker",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.facility",
                verbose_name="Bina/Birim",
            ),
        ),
    ]
