# Generated by Django 4.2.27 on 2025-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_facility_worker_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="chronic_diseases",
        ),
        migrations.AlterField(
            model_name="worker",
            name="first_aid_certificate",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="İlkyardım Sertifikası"
            ),
        ),
    ]
