# Generated by Django 4.2.27 on 2025-12-31 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_remove_worker_chronic_diseases_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="İşlem")),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Veri Türü"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Kayıt ID"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="Detaylar"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşlem Kaydı",
                "verbose_name_plural": "İşlem Kayıtları",
                "ordering": ["-timestamp"],
            },
        ),
    ]
