# Generated by Django 4.2.27 on 2025-12-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_actionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Global", max_length=255, verbose_name="Şablon Adı"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Arkaplan Resmi",
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Yerleşim Ayarları"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifika Şablonu",
                "verbose_name_plural": "Sertifika Şablonları",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="educator",
        ),
        migrations.AddField(
            model_name="education",
            name="duration",
            field=models.PositiveIntegerField(default=4, verbose_name="Süre (Saat)"),
        ),
        migrations.AddField(
            model_name="education",
            name="professionals",
            field=models.ManyToManyField(
                to="core.professional", verbose_name="Eğiticiler"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "İşyeri Hekimi"),
                    ("SPECIALIST", "İş Güvenliği Uzmanı"),
                    ("OTHER_HEALTH", "Diğer Sağlık Personeli"),
                ],
                max_length=20,
                verbose_name="Görevi",
            ),
        ),
        migrations.DeleteModel(
            name="Educator",
        ),
    ]
