# Generated by Django 4.2.27 on 2026-01-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_certificatetemplate_remove_education_educator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="layout_config",
        ),
        migrations.RemoveField(
            model_name="examination",
            name="tetanus_date",
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="html_content",
            field=models.TextField(
                default='<div style="width: 100%; max-width: 800px; padding: 40px; border: 5px solid #5d7083; font-family: \'Times New Roman\', serif; background-color: #fff; position: relative; margin: 0 auto;">\n\n  <div style="text-align: center; color: #c62828; font-size: 10pt; font-weight: bold; margin-bottom: 20px;">\n    T.C. Sağlık Bakanlığı<br>\n    Balıkesir İl Sağlık Müdürlüğü, Karesi Çalışan Sağlığı Merkezi\n  </div>\n\n  <div style="text-align: center; color: #1f3a58; font-size: 32pt; margin-bottom: 40px; letter-spacing: 2px;">\n    EĞİTİM BELGESİ\n  </div>\n\n  <div style="margin-bottom: 40px; padding-left: 20px;">\n    <div style="font-weight: bold; font-size: 12pt; line-height: 1.8;">\n      Say&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{SAYI}}<br>\n      TCKN&nbsp;&nbsp;: {{TCKN}}<br>\n      Tarih&nbsp;&nbsp;&nbsp;: {{TARIH}}<br>\n      Süre&nbsp;&nbsp;&nbsp;&nbsp;: {{SURE}}<br>\n      İş Yeri : {{IS_YERI}}\n    </div>\n  </div>\n\n  <div style="text-align: center; border-bottom: 1px solid #000; width: 60%; margin: 0 auto 20px auto; font-size: 18pt; font-weight: bold;">\n    {{AD_SOYAD}}\n  </div>\n\n  <div style="text-align: center; font-size: 11pt; color: #444; margin-bottom: 30px; padding: 0 40px;">\n    Yukarıda adı geçen çalışan,<br>\n    Çalışanların İş Sağlığı ve Güvenliği Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik\n    kapsamında verilen örgün <strong>İş Sağlığı ve Güvenliği Eğitimini</strong> başarıyla tamamlayarak bu\n    belgeyi almaya hak kazanmıştır.\n  </div>\n\n  <div style="text-align: center; font-weight: bold; font-size: 12pt; margin-bottom: 10px; font-variant: small-caps;">\n    Eğitim Konuları\n  </div>\n  \n  <div style="text-align: center; color: #fdd835; margin-bottom: 20px; font-size: 20px;">\n    ~ ☚ ~\n  </div>\n\n  <table style="width: 100%; font-size: 8pt; border-collapse: collapse; margin-bottom: 50px; margin-left: auto; margin-right: auto; border: none;">\n    <tr>\n      <td style="width: 50%; vertical-align: top; padding-right: 15px; border: none; text-align: left;">\n        Çalışma mevzuatı ile ilgili bilgiler<br>\n        Çalışanların yasal hak ve sorumlulukları<br>\n        İş yeri temizliği ve düzeni<br>\n        İş kazası ve meslek hastalıklarından doğan hukuki sonuçlar<br>\n        Meslek hastalıklarının sebebi<br>\n        Hastalıktan korunma prensip ve tekniklerinin uygulanması<br>\n        Biyolojik ve psikososyal risk etmenleri<br>\n        İlk yardım<br>\n        Tütün ürünlerinin zararları ve pasif etkilenim<br>\n        Kimyasal fiziksel risk etmenleri<br>\n        Elle kaldırma taşıma\n      </td>\n      <td style="width: 50%; vertical-align: top; padding-left: 15px; border: none; text-align: left;">\n        Patlama, patlama, yangın ve yangından korunma<br>\n        İş ekipmanlarının güvenli kullanımı<br>\n        Ekranlı araçlarla çalışma<br>\n        Elektrik tehlikeleri riskleri ve önlemleri<br>\n        İş kazası sebepleri ve korunma prensipleri ile tekniklerinin uygulanması<br>\n        Güvenlik ve sağlık işaretleri<br>\n        Kişisel koruyucu donanımın kullanımı<br>\n        İş sağlığı ve güvenliği genel kuralları ve güvenlik kültürü<br>\n        Tahliye kurtarma<br>\n        Yüksekte çalışma<br>\n        Kapalı ortamda çalışma\n      </td>\n    </tr>\n  </table>\n\n  <table style="width: 100%;  text-align: center; font-size: 10pt; color: #555; margin-top: 40px; margin-left: auto; margin-right: auto; border: none;">\n    <tr>\n      <td style="width: 33%; vertical-align: bottom; border: none;">\n        <div style="border-top: 1px solid #555; width: 90%; margin: 0 auto; padding-top: 5px;">\n          İş Güvenliği Uzmanı\n        </div>\n      </td>\n      <td style="width: 33%; vertical-align: bottom; border: none;">\n        <div style="border-top: 1px solid #555; width: 99%; margin: 0 auto; padding-top: 5px;">\n          İş Yeri Hekimi/Hemşiresi\n        </div>\n      </td>\n      <td style="width: 33%; vertical-align: bottom; border: none;">\n        <div style="border-top: 1px solid #555; width: 90%; margin: 0 auto; padding-top: 5px;">\n          İşveren/İşveren Vekili\n        </div>\n      </td>\n    </tr>\n  </table>\n\n</div>\n',
                verbose_name="HTML Şablonu",
            ),
        ),
    ]
