# Generated by Django 4.2.27 on 2026-01-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_certificatetemplate_background_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="html_content",
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="education_topics",
            field=models.TextField(
                default="Çalışma mevzuatı ile ilgili bilgiler\nÇalışanların yasal hak ve sorumlulukları\nİş yeri temizliği ve düzeni\nİş kazası ve meslek hastalıklarından doğan hukuki sonuçlar\nMeslek hastalıklarının sebebi\nHastalıktan korunma prensip ve tekniklerinin uygulanması\nBiyolojik ve psikososyal risk etmenleri\nİlk yardım\nTütün ürünlerinin zararları ve pasif etkilenim\nKimyasal fiziksel risk etmenleri\nElle kaldırma taşıma\nPatlama, patlama, yangın ve yangından korunma\nİş ekipmanlarının güvenli kullanımı\nEkranlı araçlarla çalışma\nElektrik tehlikeleri riskleri ve önlemleri\nİş kazası sebepleri ve korunma prensipleri ile tekniklerinin uygulanması\nGüvenlik ve sağlık işaretleri\nKişisel koruyucu donanımın kullanımı\nİş sağlığı ve güvenliği genel kuralları ve güvenlik kültürü\nTahliye kurtarma\nYüksekte çalışma\nKapalı ortamda çalışma",
                verbose_name="Eğitim Konuları (Her satıra bir konu)",
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="institute_name",
            field=models.TextField(
                default="T.C. Sağlık Bakanlığı\\nBalıkesir İl Sağlık Müdürlüğü, Karesi Çalışan Sağlığı Merkezi",
                verbose_name="Kurum Başlığı (Satır boşlukları için Enter kullanın)",
            ),
        ),
    ]
