# Generated by Django 4.2.27 on 2026-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_certificatetemplate_html_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatetemplate",
            name="institute_name",
            field=models.TextField(
                default="T.C. Sağlık Bakanlığı\\nBalıkesir İl Sağlık Müdürlüğü\\nKaresi Çalışan Sağlığı Merkezi",
                verbose_name="Kurum Başlığı (Satır boşlukları için Enter kullanın)",
            ),
        ),
    ]
