# Generated by Django 4.2.27 on 2026-01-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_facility_address_facility_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="employer_representative",
            field=models.TextField(
                blank=True, null=True, verbose_name="İşveren / İşveren Temsilcisi"
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="İletişim Numarası"
            ),
        ),
    ]
