# Generated by Django 4.2.27 on 2026-01-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_workplace_employer_representative_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="longitude",
        ),
        migrations.AddField(
            model_name="facility",
            name="coordinates",
            field=models.CharField(
                blank=True,
                help_text="Örn: 39.6425, 27.9152",
                max_length=100,
                null=True,
                verbose_name="Koordinatlar",
            ),
        ),
    ]
