# Generated by Django 4.2.27 on 2026-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_facility_latitude_remove_facility_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='activity_description',
            field=models.TextField(blank=True, null=True, verbose_name='Faaliyet Tanımı'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='address',
            field=models.TextField(default='', verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='nace_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NACE Kodu'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='detsis_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='SGK Sicil No / DETSİS No'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employer_representative',
            field=models.TextField(default='', verbose_name='İşveren Vekili'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İş Yeri Unvanı'),
        ),
    ]
