# Generated by Django 4.2.27 on 2026-01-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workplace_activity_description_workplace_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Araç Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sektör')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risk Değerlendirme Aracı',
                'verbose_name_plural': 'Risk Değerlendirme Araçları',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RiskTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Konu Başlığı')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.risktool', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Risk Konusu',
                'verbose_name_plural': 'Risk Konuları',
                'ordering': ['tool', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='RiskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Soru İçeriği')),
                ('explanation_text', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Görsel URL')),
                ('legal_reference', models.TextField(blank=True, verbose_name='Yasal Dayanak')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.risktopic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Risk Sorusu',
                'verbose_name_plural': 'Risk Soruları',
                'ordering': ['topic', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Değerlendirme Adı')),
                ('status', models.CharField(choices=[('DRAFT', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='core.facility', verbose_name='Birim')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.risktool', verbose_name='Değerlendirme Aracı')),
            ],
            options={
                'verbose_name': 'Değerlendirme Oturumu',
                'verbose_name_plural': 'Değerlendirme Oturumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, choices=[('YES', 'Evet'), ('NO', 'Hayır'), ('POSTPONED', 'Ertelenmiş'), ('NA', 'Uygulanamaz')], max_length=20, null=True, verbose_name='Yanıt')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskquestion', verbose_name='Soru')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.assessmentsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Değerlendirme Yanıtı',
                'verbose_name_plural': 'Değerlendirme Yanıtları',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
