# Generated by Django 4.2.27 on 2026-01-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_risktool_risktopic_riskquestion_assessmentsession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risktopic',
            options={'ordering': ['category', 'order_index'], 'verbose_name': 'Risk Konusu', 'verbose_name_plural': 'Risk Konuları'},
        ),
        migrations.RemoveField(
            model_name='risktopic',
            name='tool',
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.risktool', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Risk Kategorisi',
                'verbose_name_plural': 'Risk Kategorileri',
                'ordering': ['tool', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='risktopic',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.riskcategory', verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
