# Generated by Django 4.2.27 on 2026-01-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_risktopic_options_remove_risktopic_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCustomRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Risk Tanımı')),
                ('is_acceptable', models.BooleanField(blank=True, null=True, verbose_name='Kabul Edilebilir mi?')),
                ('evidence', models.TextField(blank=True, verbose_name='Bilgi / Kanıt')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_risks', to='core.assessmentsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Ek Risk',
                'verbose_name_plural': 'Ek Riskler',
                'ordering': ['created_at'],
            },
        ),
    ]
