# Generated by Django 4.2.27 on 2026-01-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assessmentcustomrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='risk_priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük')], max_length=10, null=True, verbose_name='Risk Önceliği'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='risk_priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük')], max_length=10, null=True, verbose_name='Risk Önceliği'),
        ),
        migrations.CreateModel(
            name='ActionPlanMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Önlem Açıklaması')),
                ('expertise', models.CharField(blank=True, max_length=200, verbose_name='Gerekli Uzmanlık')),
                ('responsible_person', models.CharField(blank=True, max_length=200, verbose_name='Sorumlu Kişi')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Bütçe')),
                ('planning_start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('planning_end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='core.assessmentanswer', verbose_name='Standart Risk')),
                ('custom_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_measures', to='core.assessmentcustomrisk', verbose_name='Ek Risk')),
            ],
            options={
                'verbose_name': 'Eylem Planı Önlemi',
                'verbose_name_plural': 'Eylem Planı Önlemleri',
                'ordering': ['created_at'],
            },
        ),
    ]
