# Generated by Django 4.2.27 on 2026-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_assessmentanswer_risk_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='final_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Sonuç Yorumları'),
        ),
    ]
