# Generated by Django 4.2.27 on 2026-01-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_assessmentsession_final_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='participants',
            field=models.TextField(blank=True, null=True, verbose_name='Katılımcılar'),
        ),
        migrations.CreateModel(
            name='RiskAssessmentTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYER', 'İşveren / Vekili'), ('SAFETY_EXPERT', 'İSG Uzmanı'), ('DOCTOR', 'İş Yeri Hekimi'), ('WORKER_REP', 'Çalışan Temsilcisi'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Rol')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Unvan')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.assessmentsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Değerlendirme Ekibi Üyesi',
                'verbose_name_plural': 'Değerlendirme Ekibi Üyeleri',
                'ordering': ['role', 'name'],
            },
        ),
    ]
