# Generated by Django 4.2.27 on 2026-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_assessmentsession_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='legal_basis',
            field=models.TextField(blank=True, verbose_name='Yasal Dayanak'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='source_library_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kütüphane ID'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='mode',
            field=models.CharField(choices=[('STANDARD', 'Standart'), ('FAST_TRACK', 'Listeden Seçerek')], default='STANDARD', max_length=20, verbose_name='Mod'),
        ),
    ]
