# Generated by Django 4.2.27 on 2026-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fast_track_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentcustomrisk',
            options={'ordering': ['created_at'], 'verbose_name': 'Risk', 'verbose_name_plural': 'Riskler'},
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='hazard_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tehlike Kaynağı'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Frekans (F)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='Olasılık (P)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kinney Skoru'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şiddet (S)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_probability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Olasılık (1-5)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Skoru'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şiddet (1-5)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='scoring_method',
            field=models.CharField(blank=True, choices=[('KINNEY', 'Fine-Kinney'), ('MATRIX', 'L-Matrix')], max_length=10, verbose_name='Puanlama Yöntemi'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Üst Kategori'),
        ),
    ]
