# Generated by Django 4.2.27 on 2026-01-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_scoring_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsession',
            name='mode',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='scoring_method',
            field=models.CharField(choices=[('KINNEY', 'Fine-Kinney'), ('MATRIX', 'L-Matris (5x5)')], default='KINNEY', max_length=10, verbose_name='Puanlama Yöntemi'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='workflow_type',
            field=models.CharField(choices=[('LIBRARY', 'Kütüphaneden Seçerek'), ('TEMPLATE', 'Hazır Şablon İle')], default='LIBRARY', max_length=20, verbose_name='Yöntem'),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.risktool', verbose_name='Değerlendirme Aracı'),
        ),
    ]
