# Generated by Django 4.2.27 on 2026-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_assessment_workflow_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='affected_persons',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etkilenecek Kişiler'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin Tarihi'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='measure',
            field=models.TextField(blank=True, verbose_name='Alınması Gereken Önlem'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sorumlu Kişi'),
        ),
    ]
