# Generated by Django 4.2.27 on 2026-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_risk_control_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tahmini Bütçe'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='mitigation_strategy',
            field=models.CharField(blank=True, choices=[('ELIMINATE', 'Yok Etme'), ('SUBSTITUTE', 'Yerine Koyma'), ('ENGINEERING', 'Mühendislik Kontrolleri'), ('ADMINISTRATIVE', 'İdari Önlemler'), ('PPE', 'KKD Kullanımı')], max_length=20, verbose_name='Kontrol Stratejisi'),
        ),
    ]
