# Generated by Django 4.2.27 on 2026-01-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_dof_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField(verbose_name='Kontrol Tarihi')),
                ('auditor_name', models.CharField(max_length=255, verbose_name='Denetleyen')),
                ('observation_note', models.TextField(blank=True, verbose_name='Gözlemler')),
                ('kinney_probability', models.FloatField(blank=True, null=True, verbose_name='Olasılık (P)')),
                ('kinney_frequency', models.FloatField(blank=True, null=True, verbose_name='Frekans (F)')),
                ('kinney_severity', models.IntegerField(blank=True, null=True, verbose_name='Şiddet (S)')),
                ('residual_score', models.IntegerField(blank=True, null=True, verbose_name='Kalan Risk Skoru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_records', to='core.assessmentcustomrisk', verbose_name='Risk')),
            ],
            options={
                'verbose_name': 'Risk Kontrol Kaydı',
                'verbose_name_plural': 'Risk Kontrol Kayıtları',
                'ordering': ['-control_date', '-created_at'],
            },
        ),
    ]
