# Generated by Django 4.2.27 on 2026-01-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_riskcontrolrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcontrolrecord',
            name='matrix_probability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Olasılık (1-5)'),
        ),
        migrations.AddField(
            model_name='riskcontrolrecord',
            name='matrix_severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Şiddet (1-5)'),
        ),
        migrations.AddField(
            model_name='riskcontrolrecord',
            name='scoring_method',
            field=models.CharField(blank=True, max_length=10, verbose_name='Puanlama Yöntemi'),
        ),
    ]
