# Generated by Django 4.2.27 on 2026-01-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_control_record_matrix_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='egitim_yeri',
            field=models.IntegerField(choices=[(1, 'İş Yerinde'), (0, 'İş Yeri Dışında')], default=1, verbose_name='Eğitim Yeri'),
        ),
        migrations.AddField(
            model_name='education',
            name='egitim_yontemi',
            field=models.IntegerField(choices=[(1, 'Yüz Yüze Eğitim'), (0, 'Uzaktan Eğitim')], default=1, verbose_name='Eğitim Yöntemi'),
        ),
        migrations.AddField(
            model_name='professional',
            name='tckn',
            field=models.CharField(default='00000000000', help_text='11 haneli TC Kimlik Numarası', max_length=11, verbose_name='TCKN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='sgk_sicil_no',
            field=models.CharField(blank=True, help_text='26 haneli SGK sicil numarası', max_length=26, verbose_name='SGK Sicil No (İBYS)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.PositiveIntegerField(default=8, help_text='Toplam eğitim süresi', verbose_name='Süre (Saat)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='topic',
            field=models.CharField(blank=True, help_text='Genel eğitim başlığı (opsiyonel)', max_length=255, verbose_name='Konu Başlığı'),
        ),
        migrations.CreateModel(
            name='EducationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_code', models.CharField(choices=[('110', '110 - Çalışma mevzuatı ile ilgili bilgiler'), ('120', '120 - Çalışanların yasal hak ve sorumlulukları'), ('130', '130 - İşyeri temizliği ve düzeni'), ('140', '140 - İş kazası ve meslek hastalığından doğan hukuki sonuçlar'), ('210', '210 - Meslek hastalıklarının sebepleri'), ('220', '220 - Hastalıktan korunma prensipleri'), ('230', '230 - Biyolojik ve psikososyal risk etmenleri'), ('240', '240 - İlkyardım'), ('250', '250 - Tütün ürünlerinin zararları'), ('310', '310 - Kimyasal, fiziksel ve ergonomik riskler'), ('320', '320 - Elle kaldırma ve taşıma'), ('330', '330 - Parlama, patlama, yangın ve korunma'), ('340', '340 - İş ekipmanlarının güvenli kullanımı'), ('350', '350 - Ekranlı araçlarla çalışma'), ('360', '360 - Elektrik tehlikeleri, riskleri ve önlemleri'), ('370', '370 - İş kazalarının sebepleri ve korunma'), ('380', '380 - Güvenlik ve sağlık işaretleri'), ('390', '390 - Kişisel koruyucu donanım kullanımı'), ('395', '395 - İSG genel kuralları ve güvenlik kültürü'), ('399', '399 - Tahliye ve kurtarma')], max_length=3, verbose_name='Eğitim Kodu')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Süre (Dakika)')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_topics', to='core.education', verbose_name='Eğitim')),
            ],
            options={
                'verbose_name': 'Eğitim Konusu',
                'verbose_name_plural': 'Eğitim Konuları',
                'unique_together': {('education', 'topic_code')},
            },
        ),
    ]
