# Generated by Django 4.2.27 on 2026-01-12 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_uuids_for_existing_facilities(apps, schema_editor):
    """Generate unique UUIDs for existing Facility records"""
    Facility = apps.get_model('core', 'Facility')
    for facility in Facility.objects.all():
        facility.uuid = uuid.uuid4()
        facility.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_ibys_integration'),
    ]

    operations = [
        # Step 1: Add uuid field without unique constraint
        migrations.AddField(
            model_name='facility',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Benzersiz Kimlik'),
        ),
        # Step 2: Generate unique UUIDs for existing records
        migrations.RunPython(generate_uuids_for_existing_facilities, migrations.RunPython.noop),
        # Step 3: Make the field non-nullable and unique
        migrations.AlterField(
            model_name='facility',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Benzersiz Kimlik'),
        ),
        migrations.CreateModel(
            name='SafetyPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('options', models.JSONField(default=list, verbose_name='Seçenekler')),
                ('votes', models.JSONField(default=dict, verbose_name='Oylar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_polls', to='core.facility', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Güvenlik Anketi',
                'verbose_name_plural': 'Güvenlik Anketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('SUGGESTION', 'Öneri'), ('NEAR_MISS', 'Ramak Kala'), ('HAZARD', 'Tehlike'), ('COMPLAINT', 'Şikayet')], max_length=20, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonim mi?')),
                ('is_public_on_wall', models.BooleanField(default=False, verbose_name='Panoda Göster')),
                ('management_response', models.TextField(blank=True, verbose_name='Yönetim Cevabı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm Tarihi')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_engagements', to='core.facility', verbose_name='Birim')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Güvenlik Bildirimi',
                'verbose_name_plural': 'Güvenlik Bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
