# Generated by Django 4.2.27 on 2026-01-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_facility_uuid_safetypoll_safetyengagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyengagement',
            name='management_response',
        ),
        migrations.AddField(
            model_name='safetyengagement',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Beğeni Sayısı'),
        ),
        migrations.CreateModel(
            name='EngagementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Yazar')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('is_professional', models.BooleanField(default=False, verbose_name='Uzman mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.safetyengagement', verbose_name='Bildirim')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['created_at'],
            },
        ),
    ]
