# Generated by Django 4.2.27 on 2026-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_engagement_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyengagement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='APPROVED', max_length=20, verbose_name='Durum'),
        ),
    ]
