# Generated by Django 4.2.27 on 2026-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_status_to_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcomment',
            name='is_public_on_voice',
            field=models.BooleanField(default=False, verbose_name="Voice'da Göster"),
        ),
    ]
