# Generated by Django 4.2.27 on 2026-01-24 08:09

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_public_on_voice_to_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='audiometry',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Odyometri'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='biochemistry',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Biyokimya'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='caution_note',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=encrypted_model_fields.fields.EncryptedDateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='decision',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('FIT', 'Çalışmaya Elverişlidir'), ('CONDITIONAL', 'Şartlı Olarak Çalışmaya Elverişlidir')], default='FIT', verbose_name='Karar'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='decision_conditions',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Şartlar'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='hemogram',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Hemogram'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='hepatitis_b_vaccine',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Hepatit B Aşısı Önerildi'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='is_caution',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Uyarı notu'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Notlar/Sonuç'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='radiology',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Radyoloji'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='serology',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Seroloji'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='sft',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='SFT'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='tetanus_vaccine',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='Tetanoz Aşısı Önerildi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tckn',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='TCKN'),
        ),
    ]
