# Generated by Django 4.2.27 on 2026-01-24 11:24

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_encrypted_fields_kvkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='coordinates',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Örn: 39.6425, 27.9152', null=True, verbose_name='Koordinatlar'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Bina/Birim Adı'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='license_id',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Lisans No'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='tckn',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='11 haneli TC Kimlik Numarası', verbose_name='TCKN'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_aid_certificate',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, default=False, verbose_name='İlkyardım Sertifikası'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_aid_expiry_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Sertifika Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, choices=[('F', 'Kadın'), ('M', 'Erkek')], null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='activity_description',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Faaliyet Tanımı'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(default='', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='detsis_number',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='SGK Sicil No / DETSİS No'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employer_representative',
            field=encrypted_model_fields.fields.EncryptedCharField(default='', verbose_name='İşveren Vekili'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='nace_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='NACE Kodu'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='İş Yeri Unvanı'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='İletişim Numarası'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='sgk_sicil_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='26 haneli SGK sicil numarası', verbose_name='SGK Sicil No (İBYS)'),
        ),
    ]
