# Generated by Django 4.2.27 on 2026-01-24 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_alter_facility_address_alter_facility_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentcustomrisk',
            options={'verbose_name': 'Siteye Özel Risk', 'verbose_name_plural': 'Siteye Özel Riskler'},
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='affected_persons',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='hazard_source',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='kinney_frequency',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='kinney_probability',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='kinney_score',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='kinney_severity',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='legal_basis',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='matrix_probability',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='matrix_score',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='matrix_severity',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='mitigation_strategy',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='risk_priority',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='source_library_id',
        ),
        migrations.RemoveField(
            model_name='assessmentcustomrisk',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük')], max_length=10, null=True, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='assessmentcustomrisk',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='Bilgi/Kanıt'),
        ),
        migrations.AlterField(
            model_name='assessmentcustomrisk',
            name='scoring_method',
            field=models.CharField(choices=[('KINNEY', 'Fine-Kinney'), ('MATRIX', 'L-Matrix')], default='KINNEY', max_length=10, verbose_name='Puanlama Yöntemi'),
        ),
        migrations.CreateModel(
            name='WorkplaceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atama Rolü (Opsiyonel)')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.workplace', verbose_name='İşyeri')),
            ],
            options={
                'verbose_name': 'İşyeri Ataması',
                'verbose_name_plural': 'İşyeri Atamaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Yönetici (Admin)'), ('MANAGER', 'Genel Müdür'), ('DOCTOR', 'İşyeri Hekimi'), ('SPECIALIST', 'İş Güvenliği Uzmanı'), ('HR', 'İK Müdürü'), ('FIELD', 'Saha Personeli')], default='SPECIALIST', max_length=20, verbose_name='Rol')),
                ('tckn', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='TCKN')),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Telefon')),
                ('is_mfa_enabled', models.BooleanField(default=False, verbose_name='2FA Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
