# Generated by Django 4.2.27 on 2026-02-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_assessmentcustomrisk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='affected_persons',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Etkilenecek Kişiler'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='category',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin Tarihi'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tahmini Bütçe'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='hazard_source',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Tehlike Kaynağı'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Frekans (F)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='Olasılık (P)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kinney Skoru'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='kinney_severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şiddet (S)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='legal_basis',
            field=models.TextField(blank=True, default='', verbose_name='İlgili Mevzuat'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_probability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Olasılık (1-5)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Skoru'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='matrix_severity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matris Şiddet (1-5)'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='measure',
            field=models.TextField(blank=True, default='', verbose_name='Alınması Gereken Önlem'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='mitigation_strategy',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Kontrol Stratejisi'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sorumlu Kişi'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='source_library_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kütüphane ID'),
        ),
        migrations.AddField(
            model_name='assessmentcustomrisk',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Üst Grup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('MANAGER', 'Yardımcı Yönetici'), ('DOCTOR', 'İş Yeri Hekimi'), ('SPECIALIST', 'İş Güvenliği Uzmanı')], default='SPECIALIST', max_length=20, verbose_name='Rol'),
        ),
    ]
